who_am_i: Slobodan Kovačević
what_am_i: Ruby on Rails developer

resume:
  - company: AxiomQ
    position: CTO / Head of Software Engineering
    description: Merged two companies to create <a href="https://axiomq.com">AxiomQ</a>. Integrated existing dev teams and expanded them further.
    start_year: 2017
    end_year: Present
    start_month: May
    end_month: Present
  - company: Orange Iceberg
    position: Project manager/Lead developer
    description: Expanded <a href="http://orangeiceberg.com">Orange Iceberg</a> a Ruby development company and built a team of 5 Ruby developers. Worked as a project manager and lead developer.
    start_year: 2014
    end_year: 2017
    start_month: Jan
    end_month: May
  - company: Earth.org GmbH
    position: Ruby developer
    description: Worked on maintaining and updating yoga.info. Created a JSON service based arhitecture to run both yoga.info and ayurvedafinder.com using the same service.
    start_year: 2012
    end_year: 2014
    start_month: June
    end_month: Jan
  - company: Reciprocity Inc.
    position: Ruby developer
    description: Worked as a Senior Engineer (Ruby on Rails) on <a href="http://www.reciprocitynow.com/">Reciprocity gamification app</a>, opower.com, sonatype.com and briefly on Google's GRC project.
    start_year: 2011
    end_year: 2014
    start_month: Feb
    end_month: Jan
  - company: Orange Iceberg
    position: Freelance Ruby developer
    description: In June 2008 I went back to freelancing as a <strong>Ruby/Rails web developer</strong>, through my own one-man company - <a href="http://orangeiceberg.com">Orange Iceberg web development</a>.
    start_year: 2008
    end_year: 2011
    start_month: Jun
    end_month: Feb
  - company: Array Studio
    position: CEO/Lead developer
    description: In September 2001 I co-founded <a href="http://www.arraystudio.com">Array Studio</a> (a web development company) where I worked as CEO and lead developer until June 2008.
    start_year: 2001
    end_year: 2008
    start_month: Sep
    end_month: Jun
  - company: Student/Freelancer
    position: Freelance developer
    description: From 1998 to 2001 I have worked as a freelance web developer, while studying Computer Science.
    start_year: 1998
    end_year: 2001
    start_month:
    end_month:

title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
